librechat:
  image:
    repository: danny-avila/librechat
    registry: ghcr.io
    tag: "v0.7.6"

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 0m
    hosts:
      - host: &host librechat.zanelab.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: librechat-tls-certificate
        hosts:
          - *host

  librechat-rag-api:
    enabled: true

  librechat:
    configEnv:
      BEDROCK_AWS_DEFAULT_REGION: "us-east-1"
      ALLOW_REGISTRATION: "true"
      BEDROCK_AWS_MODELS: "us.anthropic.claude-3-5-sonnet-20241022-v2:0,us.anthropic.claude-3-5-haiku-20241022-v1:0"
    configYamlContent: |
      version: 1.0.8 
      cache: true
      endpoints:
        bedrock:
          availableRegions:
            - "us-east-1"
            - "us-west-2"
          titleModel: "us.anthropic.claude-3-5-sonnet-20241022-v2:0,us.anthropic.claude-3-5-haiku-20241022-v1:0"
