mongodb:
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 8.0.4-debian-12-r1
  auth:
    existingSecret: mongodb-es
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 8Gi
