apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: librechat-es
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: librechat-credentials-env
  data:
  - secretKey: CREDS_IV
    remoteRef:
      key: secret/librechat
      property: CREDS_IV
  - secretKey: CREDS_KEY
    remoteRef:
      key: secret/librechat
      property: CREDS_KEY
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: secret/librechat
      property: JWT_REFRESH_SECRET
  - secretKey: JWT_SECRET
    remoteRef:
      key: secret/librechat
      property: JWT_SECRET
  - secretKey: MEILI_MASTER_KEY
    remoteRef:
      key: secret/librechat
      property: MEILI_MASTER_KEY
  - secretKey: BEDROCK_AWS_ACCESS_KEY_ID
    remoteRef:
      key: secret/librechat
      property: BEDROCK_AWS_ACCESS_KEY_ID
  - secretKey: BEDROCK_AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: secret/librechat
      property: BEDROCK_AWS_SECRET_ACCESS_KEY