apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mongodb-es
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mongodb-es
  data:
  - secretKey: mongodb-root-password
    remoteRef:
      key: secret/mongodb
      property: mongodb-root-password