apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: woodpecker-es
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: woodpecker-es
  data:
  - secretKey: WOODPECKER_GITEA_SECRET
    remoteRef:
      key: secret/woodpecker
      property: WOODPECKER_GITEA_SECRET